---
services:
  backend:
    image: bloglist-backend-dev
    container_name: bloglist-backend-dev
    build:
      context: ./bloglist-backend
      dockerfile: dev.Dockerfile
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:mongo@mongodb:27017/bloglist
    volumes:
      - ./bloglist-backend:/usr/src/app
    links:
      - mongodb:mongodb

  frontend:
    image: bloglist-frontend-dev
    container_name: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend
      dockerfile: dev.Dockerfile
    environment:
      - PORT=3000
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
      - WDS_SOCKET_PORT=8080
    volumes:
      - ./bloglist-frontend:/usr/src/app

  mongodb:
    image: mongo
    container_name: bloglist-mongodb-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=bloglist
    volumes:
      - mongodb-data-dev:/data/db
      - ./bloglist-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  nginx:
    image: nginx:1.21
    container_name: bloglist-nginx-dev
    ports:
      - "127.0.0.1:8080:80"
    links:
      - frontend
      - backend
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongodb-data-dev:
